swagger: '2.0'
info:
  title: Accounting System API
  description: API for Accounting System
  version: "1.0.0"
schemes:
  - http
basePath: /api
definitions:
  RAData:
    type: object
    required:
      - user_id
      - user_name
      - user_num
      - email_address
      - year
      - semester
      - house_name
    properties:
      user_id:
        type: integer
        description: The unique identifier for the RA.
      user_name:
        type: string
        description: The name of the RA.
      user_num:
        type: string
        description: The contact number of the RA.
      division_num:
        type: integer
        description: The division number of the RA, if applicable.
      email_address:
        type: string
        description: The email address of the RA.
      year:
        type: integer
        description: The academic year of the RA.
      semester:
        type: integer
        description: 1 if the semester is spring, 2 if fall.
      house_name:
        type: string
        description: The name of the house or dormitory.
      authority:
        type: boolean
        description: True if Head RA or Accounting RA
  ProgramData:
    type: object
    required:
      - program_id
      - program_name
      - house_name
      - year
      - semester
      - year_semester_house
    properties:
      program_id:
        type: string
        description: year-semester-housecode-serialnumber
      program_name:
        type: string
        description: Program name
      house_name:
        type: string
        description: house code in english
      year:
        type: integer
      semester:
        type: integer
      register_check:
        type: boolean
        description: if the program registered at first
      year_semester_house:
        type: string
        description: 색인을 위한 코드.
  ReceiptSubmission:
    type: object
    required:
      - id
      - year
      - month
      - day
      - time
      - date
      - house_name
      - user_id
      - program_id
      - category_id
      - head_count
      - expenditure
      - store_name
      - reason_store
      - isp_check
      - holiday_check
      - souvenir_record
      - division_program
      - purchase_reason
      - key_items_quantity
      - purchase_details
    properties:
      id:
        type: string
        description: "Unique identifier for the receipt submission."
      year:
        type: integer
        description: "Year of the receipt submission."
      month:
        type: integer
        description: "Month of the receipt submission."
      day:
        type: integer
        description: "Day of the receipt submission."
      time:
        type: string
        description: "Time of the receipt submission."
      date:
        type: string
        format: date-time
        description: "Exact timestamp of the receipt submission, with timezone."
      house_name:
        type: string
        description: "House name associated with the receipt submission."
      user_id:
        type: integer
        format: int64
        description: "User identifier related to the receipt submission."
      program_id:
        type: string
        description: "Program identifier related to the receipt."
      category_id:
        type: string
        description: "Category identifier related to the receipt."
      head_count:
        type: integer
        description: "Number of people covered by the receipt."
      expenditure:
        type: integer
        format: int64
        description: "Total amount spent, represented in the smallest currency unit (e.g., cents)."
      store_name:
        type: string
        description: "Name of the store where the purchase was made."
      division_num:
        type: string
        description: "Division number, if applicable."
      reason_store:
        type: string
        description: "Reason for choosing this particular store."
      isp_check:
        type: boolean
        description: "Boolean flag indicating if the ISP check was passed."
      holiday_check:
        type: boolean
        description: "Boolean flag indicating if this was a holiday purchase."
      souvenir_record:
        type: boolean
        description: "Indicates if a souvenir record was made."
      division_program:
        type: boolean
        description: "Indicates if this is part of a division program."
      purchase_reason:
        type: string
        description: "Core reason for the purchase."
      key_items_quantity:
        type: string
        description: "List of key items and their quantities."
      purchase_details:
        type: string
        description: "Detailed description of the purchase."
      created_at:
        type: string
        format: date-time
        description: "Timestamp when the receipt was created, with timezone."
      updated_at:
        type: string
        format: date-time
        description: "Timestamp when the receipt was last updated, with timezone."
      warning_division:
        type: string
        description: "Any warning or special notes about the division."

