"""Initial migration.

Revision ID: 948bc9d95f73
Revises: 
Create Date: 2024-07-16 19:57:36.320533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948bc9d95f73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_list_table')
    op.drop_table('category_list_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_list_table',
    sa.Column('category_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category_id', name='category_list_table_pkey')
    )
    op.create_table('program_list_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('house_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('register_check', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='program_list_table_pkey')
    )
    # ### end Alembic commands ###
